openapi: 3.0.0
info:
  title: Quiz Service API
  description: API cho service quiz
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1

paths:
  /quizzes:
    get:
      summary: Lấy danh sách quiz
      description: Retrieves a list of all quizzes.
      operationId: getAllQuizzes
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
          example: "Bearer your_jwt_token_here"
      responses:
        "200":
          description: A list of quizzes
          content:
            application/json:
              examples:
                application/json:
                  value:
                    - id: 1
                      title: "Dịch vụ khách hàng và quản lý dịch vụ"
                      description: "Câu hỏi về kỹ năng chăm sóc khách hàng và các mô hình quản lý dịch vụ."
                      duration: 45
                    - id: 3
                      title: "Phân tích và đo lường sự hài lòng của khách hàng"
                      description: "Câu hỏi về các phương pháp đo lường mức độ hài lòng của khách hàng."
                      duration: 50
        "401":
          description: Unauthorized

    post:
      summary: Tạo một quiz
      description: Chỉ cho phép admin
      operationId: createQuiz
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
          example: "Bearer your_jwt_token_here"
      requestBody:
        required: true
        content:
          application/json:
            examples:
              application/json:
                value:
                  title: "Dịch vụ khách hàng và quản lý dịch vụ"
                  description: "Câu hỏi về các phương pháp đo lường mức độ hài lòng của khách hàng."
                  duration: 50
      responses:
        "201":
          description: Quiz created successfully
          content:
            application/json:
              examples:
                application/json:
                  value:
                    id: 3
                    title: "History Quiz"
                    description: "A quiz on world history"
                    duration: 40
        "403":
          description: Forbidden - Only admin can create quizzes
        "401":
          description: Unauthorized

  /quizzes/{id}:
    get:
      summary: Lấy chi tiết quiz theo id
      description: Retrieves a quiz by its ID.
      operationId: getQuizById
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
          example: "Bearer your_jwt_token_here"
        - name: id
          in: path
          required: true
          description: ID of the quiz
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: A quiz
          content:
            application/json:
              examples:
                application/json:
                  value:
                    id: 1
                    title: "Câu hỏi về các phương pháp đo lường mức độ hài lòng của khách hàng."
                    description: "Câu hỏi về các phương pháp đo lường mức độ hài lòng của khách hàng."
                    duration: 30
        "401":
          description: Unauthorized
        "404":
          description: Quiz not found

    put:
      summary: Cập nhật quiz
      description: Only accessible by admin. Updates a quiz by its ID.
      operationId: updateQuiz
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
          example: "Bearer your_jwt_token_here"
        - name: id
          in: path
          required: true
          description: ID of the quiz to update
          schema:
            type: integer
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            examples:
              application/json:
                value:
                  title: "Advanced Math Quiz"
                  description: "A more challenging math quiz"
                  duration: 50
      responses:
        "200":
          description: Quiz updated successfully
        "403":
          description: Forbidden - Only admin can update quizzes
        "401":
          description: Unauthorized
        "404":
          description: Quiz not found

    delete:
      summary: Xóa một quiz theo id
      description: Only accessible by admin. Deletes a quiz by its ID.
      operationId: deleteQuiz
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
          example: "Bearer your_jwt_token_here"
        - name: id
          in: path
          required: true
          description: ID of the quiz to delete
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: Quiz deleted successfully
        "403":
          description: Forbidden - Only admin can delete quizzes
        "401":
          description: Unauthorized
        "404":
          description: Quiz not found
