openapi: 3.0.0
info:
  title: Question Service API
  description: API cho service question
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1

paths:
  /questions:
    get:
      summary: Lấy danh sách câu hỏi
      description: Chỉ cho phép admin
      operationId: getAllQuestions
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
          example: "Bearer your_jwt_token_here"
      responses:
        "200":
          description: A list of questions
          content:
            application/json:
              examples:
                application/json:
                  value:
                    - id: 1
                      quizId: 1
                      content: "Các yếu tố chính trong mô hình SERVQUAL là gì?"
                      explanation: "SERVQUAL bao gồm 5 yếu tố: Tin cậy, Đảm bảo, Hữu hình, Đồng cảm và Đáp ứng"
                      type: "MULTIPLE_CHOICE"
                    - id: 2
                      quizId: 1
                      content: "Khái niệm 'Khoảng cách dịch vụ' đề cập đến điều gì?"
                      explanation: "Khoảng cách giữa mong đợi của khách hàng và trải nghiệm thực tế"
                      type: "MULTIPLE_CHOICE"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden - Only admin can access all questions

    post:
      summary: Tạo một câu hỏi
      description: Chỉ cho phép admin
      operationId: createQuestion
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
          example: "Bearer your_jwt_token_here"
      requestBody:
        required: true
        content:
          application/json:
            examples:
              application/json:
                value:
                  quizId: 1
                  content: "Điều gì là yếu tố quan trọng nhất để đảm bảo sự hài lòng của khách hàng?"
                  explanation: "Đáp ứng mong đợi và giải quyết vấn đề nhanh chóng"
                  type: "MULTIPLE_CHOICE"
      responses:
        "201":
          description: Question created successfully
          content:
            application/json:
              examples:
                application/json:
                  value:
                    id: 3
                    quizId: 1
                    content: "Điều gì là yếu tố quan trọng nhất để đảm bảo sự hài lòng của khách hàng?"
                    explanation: "Đáp ứng mong đợi và giải quyết vấn đề nhanh chóng"
                    type: "MULTIPLE_CHOICE"
        "403":
          description: Forbidden - Only admin can create questions
        "401":
          description: Unauthorized

  /questions/{id}:
    get:
      summary: Lấy chi tiết câu hỏi theo id
      description: Accessible by both ADMIN and USER roles
      operationId: getQuestionById
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
          example: "Bearer your_jwt_token_here"
        - name: id
          in: path
          required: true
          description: ID of the question
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: A question
          content:
            application/json:
              examples:
                application/json:
                  value:
                    id: 1
                    quizId: 1
                    content: "Các yếu tố chính trong mô hình SERVQUAL là gì?"
                    explanation: "SERVQUAL bao gồm 5 yếu tố: Tin cậy, Đảm bảo, Hữu hình, Đồng cảm và Đáp ứng"
                    type: "MULTIPLE_CHOICE"
        "401":
          description: Unauthorized
        "404":
          description: Question not found

    put:
      summary: Cập nhật câu hỏi
      description: Only accessible by admin
      operationId: updateQuestion
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
          example: "Bearer your_jwt_token_here"
        - name: id
          in: path
          required: true
          description: ID of the question to update
          schema:
            type: integer
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            examples:
              application/json:
                value:
                  quizId: 1
                  content: "Các yếu tố chính trong mô hình SERVQUAL là gì? (cập nhật)"
                  explanation: "SERVQUAL bao gồm 5 yếu tố: Tin cậy, Đảm bảo, Hữu hình, Đồng cảm và Đáp ứng"
                  type: "MULTIPLE_CHOICE"
      responses:
        "200":
          description: Question updated successfully
          content:
            application/json:
              examples:
                application/json:
                  value:
                    id: 1
                    quizId: 1
                    content: "Các yếu tố chính trong mô hình SERVQUAL là gì? (cập nhật)"
                    explanation: "SERVQUAL bao gồm 5 yếu tố: Tin cậy, Đảm bảo, Hữu hình, Đồng cảm và Đáp ứng"
                    type: "MULTIPLE_CHOICE"
        "403":
          description: Forbidden - Only admin can update questions
        "401":
          description: Unauthorized
        "404":
          description: Question not found

    delete:
      summary: Xóa một câu hỏi theo id
      description: Only accessible by admin
      operationId: deleteQuestion
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
          example: "Bearer your_jwt_token_here"
        - name: id
          in: path
          required: true
          description: ID of the question to delete
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: Question deleted successfully
          content:
            application/json:
              examples:
                application/json:
                  value: "DELETED QUESTION SUCCESSFULLY"
        "403":
          description: Forbidden - Only admin can delete questions
        "401":
          description: Unauthorized
        "404":
          description: Question not found

  /questions/quiz/{quizId}:
    get:
      summary: Lấy danh sách câu hỏi theo quiz ID
      description: Accessible by both ADMIN and USER roles
      operationId: getQuestionsByQuizId
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
          example: "Bearer your_jwt_token_here"
        - name: quizId
          in: path
          required: true
          description: ID of the quiz
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: List of questions for a specific quiz
          content:
            application/json:
              examples:
                application/json:
                  value:
                    - id: 1
                      quizId: 1
                      content: "Các yếu tố chính trong mô hình SERVQUAL là gì?"
                      explanation: "SERVQUAL bao gồm 5 yếu tố: Tin cậy, Đảm bảo, Hữu hình, Đồng cảm và Đáp ứng"
                      type: "MULTIPLE_CHOICE" 
                    - id: 2
                      quizId: 1
                      content: "Khái niệm 'Khoảng cách dịch vụ' đề cập đến điều gì?"
                      explanation: "Khoảng cách giữa mong đợi của khách hàng và trải nghiệm thực tế"
                      type: "MULTIPLE_CHOICE"
        "401":
          description: Unauthorized
        "404":
          description: Quiz not found

  /questions/search:
    get:
      summary: Tìm kiếm câu hỏi
      description: Only accessible by admin
      operationId: searchQuestions
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
          example: "Bearer your_jwt_token_here"
        - name: keyword
          in: query
          required: true
          description: Search keyword
          schema:
            type: string
          example: "dịch vụ"
      responses:
        "200":
          description: List of matching questions
          content:
            application/json:
              examples:
                application/json:
                  value:
                    - id: 1
                      quizId: 1
                      content: "Các yếu tố chính trong mô hình dịch vụ SERVQUAL là gì?"
                      explanation: "SERVQUAL bao gồm 5 yếu tố: Tin cậy, Đảm bảo, Hữu hình, Đồng cảm và Đáp ứng"
                      type: "MULTIPLE_CHOICE"
                    - id: 2
                      quizId: 1
                      content: "Khái niệm 'Khoảng cách dịch vụ' đề cập đến điều gì?"
                      explanation: "Khoảng cách giữa mong đợi của khách hàng và trải nghiệm thực tế"
                      type: "MULTIPLE_CHOICE"
        "403":
          description: Forbidden - Only admin can search questions
        "401":
          description: Unauthorized